### ISSUE TITLE
网盘关闭了

### ISSUE THREAD

**Issue by MetaAIxhy** [iBcker/adcdownload#11]
360网盘都关闭了，链接已经无法访问了。

**Comment by gexiao** [comment]
新版本的 Xcode 已经不再往网盘上传了，adcdownload.apple.com 在大陆已经有 CDN，可以直接从官网下载。老版本的还有什么价值吗？

**Comment by MetaAIxhy** [comment]
系统没升级的话比较新的版本安装不了吧？虽然我最后还是选择了升级系统...

**Comment by gexiao** [comment]
如果有某个老版本的需要，可以开 issue 找我恢复。360 网盘关掉了，我总不能全都重新传一遍。
