### ISSUE TITLE
能否增加百度云盘地址?

### ISSUE THREAD

**Issue by alexlee928** [iBcker/adcdownload#6]
为什么是360云盘??可以增加百度云盘么?

**Comment by gexiao** [comment]
刚开始是放在百度盘的，XcodeGhost 的时候百度盘无脑清理文件带来很多麻烦，就换到 360云盘了。你看看这个 commit：https://github.com/iBcker/adcdownload/commit/c913933c4a45cb95ab8bc7dd599e5c0b775c4f44

如果你觉得百度盘有必要，后面的版本我可以加上。

**Comment by alexlee928** [comment]
如果能有除云盘以为的空间存放这个项目就好了,这样我使用百度云的话,直接用百度的离线下载也是蛮快的,如果是百度无脑删的话,还是保持现状挺好.
