### ISSUE TITLE
Just asking about the checksum

### ISSUE THREAD

**Issue by luohui8891** [iBcker/adcdownload#8]
@Bynil Xcode7.3的checksum你哪里找到的？我翻遍了苹果的网站也没找到这个东西。

**Comment by gexiao** [comment]
自己用浏览器走 HK 的线路从 Apple 官方源地址下载后再本地效验的，目前官方还不提供 hash 值。

**Comment by gexiao** [comment]
另外，腾讯 Bugly 团队也维护了一份国内的 Xcode 源（虽然不怎么好用总是出错），他们也提供 SHA-1 值的，思路应该和我这里一致。

![image](https://cloud.githubusercontent.com/assets/3390634/14007248/e610e31a-f1af-11e5-92a2-efeb2ffaf419.png)

[http://android-mirror.bugly.qq.com:8080/](http://android-mirror.bugly.qq.com:8080/)

**Comment by luohui8891** [comment]
还真没有啊，我还以为只有我一个人找不到呢。昨天用迅雷下载了官方的地址，还是不太放心。
