### ISSUE TITLE
能否加上各种doc的下载资源？

### ISSUE THREAD

**Issue by luohui8891** [iBcker/adcdownload#9]
比如iOS 9.3的document

**Comment by gexiao** [comment]
doc 不是 Apple Developer Center 上的内容，墙内可以下载，需求太小了。

**Comment by luohui8891** [comment]
好吧。

**Comment by puttin** [comment]
[Docset Index](https://developer.apple.com/library/downloads/docset-index.dvtdownloadableindex)

[how to install Xcode documentation by dmg file](http://stackoverflow.com/questions/29443681/how-to-install-xcode-documentation-by-dmg-file)

**Comment by luohui8891** [comment]
@puttin thanks.
I can find the download link from Charles.
Just wanna the list of new documentations and simulators in Xcode7. (Though I can also find them via Charles.)
@Bynil BTW, it's fucking slow to download resources from Apple in China including the documentations and simulators. So would you have plan to add the resources in Yunpan? Just asking.

**Comment by gexiao** [comment]
@luohui8891 I can add the latest version iOS documentation dmg file beginning with iOS 9.3. Simulators look like different in different version of Xcode, I will not add them.

**Comment by luohui8891** [comment]
@Bynil it's cool.

**Comment by gexiao** [comment]
Added. 
https://github.com/iBcker/adcdownload/commit/b4506b338350dc42c39d7f76a643d668488671bd

**Comment by luohui8891** [comment]
Downloading, thanks.
